version: '3'
services:
  front:
    build:
      context: ./Front-ExamenSonetasot
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./Front-ExamenSonetasot:/app
    command: ["npm", "run", "dev"]
  back:
    build:
      context: ./Back-ExamenSonetasot
      dockerfile: Dockerfile
    ports:
      - 4000:4000
  db:
    image: postgres:alpine3.18
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5431:5432